name: Dispatch Workflow

on: [push, pull_request]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Trigger Generate Task Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: generate_task.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            {
              "template": "Your task template here",
              "requirements": "{\"difficulty\": \"medium\", \"language\": \"Java\"}"
            }
