name: Generate Task

on:
  workflow_dispatch:
    inputs:
      theme:
        description: 'Theme for the new task'
        required: true
        default: 'Create a simple game application that includes the following functionalities: player movement, scoring system, and enemy interactions.'
      requirements:
        description: 'Requirements for the new task'
        required: true
        default: '{"difficulty": "medium", "language": "Java"}'

permissions:
  contents: write  # Grant write permission for the GITHUB_TOKEN

jobs:
  generate-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pytz

      - name: Generate new task
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS_JSON: ${{ github.event.inputs.requirements }}
          TASK_THEME: ${{ github.event.inputs.theme }}
        run: |
          python scripts/generate_task.py "${{ secrets.OPENAI_TOKEN }}"

      - name: Create branch with task content
        id: create_branch
        run: |
          branch_name="task-$(date +%Y%m%d%H%M%S)"
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          git checkout -b $branch_name
          git add tasks/new_task.md src/template_code.java
          git commit -m "Add new task"
          git push origin $branch_name

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ env.branch_name }}
          title: 'Add new task'
          body: 'This PR adds a new task based on the provided theme and requirements.'
          draft: true
