name: Grade Task Submission

on:
  pull_request:
    branches:
      - task-*

permissions:
  contents: write
  pull-requests: write

jobs:
  grade-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout task branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout student's branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: student-code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run tests
        run: |
          cd student-code/src
          javac *.java
          java org.junit.runner.JUnitCore IndamonTest

      - name: Grade and provide feedback
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/grade_submission.py "${{ secrets.OPENAI_TOKEN }}" "${{ github.event.pull_request.number }}"

      - name: Merge pull request
        if: success()
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
