name: Pull Request Review

on:
  pull_request:
    branches:
      - task-* # This triggers the workflow on PRs to task branches

permissions:
  contents: write  # Grant write permission for the GITHUB_TOKEN
  pull-requests: write  # Making sure the PR comments can be added

jobs:
  run-tests:
    runs-on: ubuntu-latest

    outputs:
      tests_passed: ${{ steps.determine-result.outputs.tests_passed }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # Ensure the branch with the new task is checked out

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # You can choose your JDK distribution
          java-version: '11'     # Adjust to the JDK version you need

      - name: Verify Branch and Test Files
        run: |
          echo "Checking out branch: ${{ github.head_ref }}"
          git branch
          ls -R .hidden_tasks

      - name: Compile the Code
        run: |
          javac -d .hidden_tasks/ .hidden_tasks/*.java src/*.java

      - name: Run Tests
        id: run-tests
        run: |
          java -cp .hidden_tasks/:path/to/junit-platform-console-standalone.jar org.junit.runner.JUnitCore .hidden_tasks.GameTest

      - name: Determine Test Result
        id: determine-result
        run: |
          if [ ${{ steps.run-tests.outcome }} == 'success' ]; then
            echo "::set-output name=tests_passed::true"
          else
            echo "::set-output name=tests_passed::false"
          fi

  analyze-and-respond:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # Ensure the same branch is checked out here

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # You can choose your JDK distribution
          java-version: '11'     # Adjust to the JDK version you need

      - name: Set GITHUB_PR_NUMBER
        run: echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Analyze and Respond
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the PAT token or GITHUB_TOKEN
          TESTS_PASSED: ${{ needs.run-tests.outputs.tests_passed }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}  
        run: |
          if [ "${{ env.TESTS_PASSED }}" == "true" ]; then
            python scripts/generate_compliment_and_merge.py "${{ secrets.OPENAI_TOKEN }}" "${{ github.head_ref }}" "${{ github.base_ref }}"
          else
            python scripts/generate_feedback_and_clues.py "${{ secrets.OPENAI_TOKEN }}" "${{ github.head_ref }}" "${{ github.base_ref }}"
          fi
