name: Pull Request Review

on:
  pull_request:
    branches:
      - task-* # This triggers the workflow on PRs to task branches

permissions:
  contents: write  # Grant write permission for the GITHUB_TOKEN

jobs:
  run-tests:
    runs-on: ubuntu-latest

    outputs:
      tests_passed: ${{ steps.determine-result.outputs.tests_passed }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run Tests
        id: run-tests
        run: |
          python -m unittest discover .hidden_tasks

      - name: Determine Test Result
        id: determine-result
        run: |
          if [ ${{ steps.run-tests.outcome }} == 'success' ]; then
            echo "::set-output name=tests_passed::true"
          else
            echo "::set-output name=tests_passed::false"
          fi

  analyze-and-respond:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Set GITHUB_PR_NUMBER
        run: echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Analyze and Respond
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTS_PASSED: ${{ env.tests_passed }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}  # Ensure it's available here
        run: |
          if [ "${{ env.TESTS_PASSED }}" == "true" ]; then
            python scripts/generate_compliment_and_merge.py "${{ secrets.OPENAI_TOKEN }}" "${{ github.head_ref }}" "${{ github.base_ref }}"
          else
            python scripts/generate_feedback_and_clues.py "${{ secrets.OPENAI_TOKEN }}" "${{ github.head_ref }}" "${{ github.base_ref }}"
          fi